GET https://7ktmwp0ell.execute-api.us-east-1.amazonaws.com/prod/spaces
###

POST https://7ktmwp0ell.execute-api.us-east-1.amazonaws.com/prod/spaces
content-type: application/json

{
  "location": "Paris"
}
###

GET https://7ktmwp0ell.execute-api.us-east-1.amazonaws.com/prod/spaces?id=275081eb-7236-471f-83ef-ee8a056a588c
###